package com.alexnevsky.facemash.storage;

import com.alexnevsky.facemash.logic.FacebookFaceManager;
import com.alexnevsky.facemash.model.Face;

import java.io.Serializable;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * User: Alex Nevsky
 * Date: 04.10.13
 */
public class Base implements Serializable {

	public static int FACES_CACHE_SIZE = 10240;

	private long[] girlsFaceIdArray;
	private long[] boysFaceIdArray;
	private final Map<Long, Face> girlsFaceMap = new ConcurrentHashMap<Long, Face>(384);
	private final Map<Long, Face> boysFaceMap = new ConcurrentHashMap<Long, Face>(384);

	private final Map<Long, Face> girlsFacebookFaceMap = Collections.synchronizedMap(new LruCache<Long, Face>(FACES_CACHE_SIZE));
	private final Map<Long, Face> boysFacebookFaceMap = Collections.synchronizedMap(new LruCache<Long, Face>(FACES_CACHE_SIZE));

	private static Base instance = new Base();

	static {
		FacebookFaceManager.addFacebookFace("galyonkin");
	}

	public static Base getInstance() {
		return instance;
	}

	public void loadBase(Base base) {
		instance = base;
	}

	/////////////////////////////////////////////////////////////////
	// Dynamic Facebook Faces
	/////////////////////////////////////////////////////////////////

	public Map<Long, Face> getGirlsFacebookFaceMap() {
		return girlsFacebookFaceMap;
	}

	public Map<Long, Face> getBoysFacebookFaceMap() {
		return boysFacebookFaceMap;
	}

	/////////////////////////////////////////////////////////////////
	// Static Celebrities Faces
	/////////////////////////////////////////////////////////////////

	public long[] getGirlsFaceIdArray() {
		return girlsFaceIdArray.clone();
	}

	public long[] getBoysFaceIdArray() {
		return boysFaceIdArray.clone();
	}

	public Map<Long, Face> getGirlsFaceMap() {
		return girlsFaceMap;
	}

	public Map<Long, Face> getBoysFaceMap() {
		return boysFaceMap;
	}

	{
		Face face;

		//girls
		face = new Face("Abbie", "Cornish", "/resources/faces/girls/Abbie_Cornish.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Adriana", "Lima", "/resources/faces/girls/Adriana_Lima.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Agnes", "Bruckner", "/resources/faces/girls/Agnes_Bruckner.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Ahna", "OReilly", "/resources/faces/girls/Ahna_OReilly.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("AJ", "Cook", "/resources/faces/girls/AJ_Cook.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Alessandra", "Ambrosio", "/resources/faces/girls/Alessandra_Ambrosio.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Alexandra", "Krosney", "/resources/faces/girls/Alexandra_Krosney.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Alexandra", "Siegel", "/resources/faces/girls/Alexandra_Siegel.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Alexis", "Knapp", "/resources/faces/girls/Alexis_Knapp.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Ali", "Larter", "/resources/faces/girls/Ali_Larter.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Alice", "Englert", "/resources/faces/girls/Alice_Englert.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Alison", "Brie", "/resources/faces/girls/Alison_Brie.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Allie", "Gonino", "/resources/faces/girls/Allie_Gonino.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Allison", "Williams", "/resources/faces/girls/Allison_Williams.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Alona", "Tal", "/resources/faces/girls/Alona_Tal.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Amanda", "Seyfried", "/resources/faces/girls/Amanda_Seyfried.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Amber", "Heard", "/resources/faces/girls/Amber_Heard.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Amrita", "Acharia", "/resources/faces/girls/Amrita_Acharia.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Amy", "Roiland", "/resources/faces/girls/Amy_Roiland.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Ana", "Beatriz Barros", "/resources/faces/girls/Ana_Beatriz_Barros.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Andi", "Muise", "/resources/faces/girls/Andi_Muise.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Andrea", "Gabriel", "/resources/faces/girls/Andrea_Gabriel.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Angela", "Besharah", "/resources/faces/girls/Angela_Besharah.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Angela", "Lindvall", "/resources/faces/girls/Angela_Lindvall.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Angelina", "Jolie", "/resources/faces/girls/Angelina_Jolie.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Anna", "Camp", "/resources/faces/girls/Anna_Camp.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Anna", "Kendrick", "/resources/faces/girls/Anna_Kendrick.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Anndi", "McAfee", "/resources/faces/girls/Anndi_McAfee.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Anne", "Hathaway", "/resources/faces/girls/Anne_Hathaway.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Annie", "Hall", "/resources/faces/girls/Annie_Hall.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Antoinette", "Kalaj", "/resources/faces/girls/Antoinette_Kalaj.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Ashleigh", "Dejon", "/resources/faces/girls/Ashleigh_Dejon.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Ashleigh", "Harrington", "/resources/faces/girls/Ashleigh_Harrington.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Ashley", "Bell", "/resources/faces/girls/Ashley_Bell.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Ashley", "Benson", "/resources/faces/girls/Ashley_Benson.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Ashley", "Greene", "/resources/faces/girls/Ashley_Greene.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Ashley", "Laurence", "/resources/faces/girls/Ashley_Laurence.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Ashley", "Schnacky", "/resources/faces/girls/Ashley_Schnacky.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Ava", "Gaudet", "/resources/faces/girls/Ava_Gaudet.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Bar", "Refaeli", "/resources/faces/girls/Bar_Refaeli.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Beatrice", "King", "/resources/faces/girls/Beatrice_King.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Beau", "Garrett", "/resources/faces/girls/Beau_Garrett.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Bella", "Heathcote", "/resources/faces/girls/Bella_Heathcote.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Blake", "Lively", "/resources/faces/girls/Blake_Lively.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Brit", "Marling", "/resources/faces/girls/Brit_Marling.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Brooke", "Butler", "/resources/faces/girls/Brooke_Butler.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Brooklyn", "Sudano", "/resources/faces/girls/Brooklyn_Sudano.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Bryce", "Dallas Howard", "/resources/faces/girls/Bryce_Dallas_Howard.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Caitlin", "Stasey", "/resources/faces/girls/Caitlin_Stasey.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Camilla", "Belle", "/resources/faces/girls/Camilla_Belle.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Candice", "Accola", "/resources/faces/girls/Candice_Accola.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Candice", "Swanepoel", "/resources/faces/girls/Candice_Swanepoel.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Cara", "Delevingne", "/resources/faces/girls/Cara_Delevingne.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Carey", "Mulligan", "/resources/faces/girls/Carey_Mulligan.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Carla", "Gallo", "/resources/faces/girls/Carla_Gallo.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Caroline", "de Souza Correa", "/resources/faces/girls/Caroline_de_Souza_Correa.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Caroline", "Dhavernas", "/resources/faces/girls/Caroline_Dhavernas.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Carrie", "Collins", "/resources/faces/girls/Carrie_Collins.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Carrie-Anne", "Moss", "/resources/faces/girls/Carrie-Anne_Moss.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Casey", "Carolan", "/resources/faces/girls/Casey_Carolan.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Cat", "Hartmann", "/resources/faces/girls/Cat_Hartmann.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Charlize", "Theron", "/resources/faces/girls/Charlize_Theron.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Chasty", "Ballesteros", "/resources/faces/girls/Chasty_Ballesteros.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Chenoa", "Mason", "/resources/faces/girls/Chenoa_Mason.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Christina", "Cannon", "/resources/faces/girls/Christina_Cannon.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Christina", "Ricci", "/resources/faces/girls/Christina_Ricci.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Christine", "Marzano", "/resources/faces/girls/Christine_Marzano.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Cindy", "Sampson", "/resources/faces/girls/Cindy_Sampson.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Cindy", "Vela", "/resources/faces/girls/Cindy_Vela.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Claire", "Julien", "/resources/faces/girls/Claire_Julien.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Claudia", "Black", "/resources/faces/girls/Claudia_Black.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Cristine", "Prosperi", "/resources/faces/girls/Cristine_Prosperi.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Dakota", "Fanning", "/resources/faces/girls/Dakota_Fanning.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Daniela", "Dib", "/resources/faces/girls/Daniela_Dib.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Daria", "Werbowy", "/resources/faces/girls/Daria_Werbowy.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Debra", "Harrison-Lowe", "/resources/faces/girls/Debra_Harrison-Lowe.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Demi", "Moore", "/resources/faces/girls/Demi_Moore.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Desi", "Ivanova", "/resources/faces/girls/Desi_Ivanova.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Diane", "Kruger", "/resources/faces/girls/Diane_Kruger.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Doutzen", "Kroes", "/resources/faces/girls/Doutzen_Kroes.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Eleanor", "Tomlinson", "/resources/faces/girls/Eleanor_Tomlinson.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Elena", "Anaya", "/resources/faces/girls/Elena_Anaya.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Eleni", "Nico", "/resources/faces/girls/Eleni_Nico.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Elisabeth", "Moss", "/resources/faces/girls/Elisabeth_Moss.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Elisabetta", "Fantone", "/resources/faces/girls/Elisabetta_Fantone.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Elisha", "Cuthbert", "/resources/faces/girls/Elisha_Cuthbert.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Elizabeth", "Hurley", "/resources/faces/girls/Elizabeth_Hurley.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Elizabeth", "Mathis", "/resources/faces/girls/Elizabeth_Mathis.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Elizabeth", "Mitchell", "/resources/faces/girls/Elizabeth_Mitchell.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Ellen", "Page", "/resources/faces/girls/Ellen_Page.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Embeth", "Davidtz", "/resources/faces/girls/Embeth_Davidtz.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Emilia", "Clarke", "/resources/faces/girls/Emilia_Clarke.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Emilie", "de Ravin", "/resources/faces/girls/Emilie_de_Ravin.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Emily", "Blunt", "/resources/faces/girls/Emily_Blunt.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Emily", "Deschanel", "/resources/faces/girls/Emily_Deschanel.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Emily", "Hampshire", "/resources/faces/girls/Emily_Hampshire.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Emily", "Kinney", "/resources/faces/girls/Emily_Kinney.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Emily", "Robison", "/resources/faces/girls/Emily_Robison.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Emily", "VanCamp", "/resources/faces/girls/Emily_VanCamp.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Emma", "Stone", "/resources/faces/girls/Emma_Stone.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Emma", "Watson", "/resources/faces/girls/Emma_Watson.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Emmanuelle", "Chriqui", "/resources/faces/girls/Emmanuelle_Chriqui.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Emmanuelle", "Vaugier", "/resources/faces/girls/Emmanuelle_Vaugier.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Emmy", "Rossum", "/resources/faces/girls/Emmy_Rossum.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Erica", "Cerra", "/resources/faces/girls/Erica_Cerra.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Erin", "Keller", "/resources/faces/girls/Erin_Keller.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Eva", "Green", "/resources/faces/girls/Eva_Green.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Eva", "Mendes", "/resources/faces/girls/Eva_Mendes.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Evangeline", "Lilly", "/resources/faces/girls/Evangeline_Lilly.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Evanna", "Lynch", "/resources/faces/girls/Evanna_Lynch.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Eve", "Hewson", "/resources/faces/girls/Eve_Hewson.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Eve", "Mauro", "/resources/faces/girls/Eve_Mauro.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Famke", "Janssen", "/resources/faces/girls/Famke_Janssen.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Flavia", "de Oliveira", "/resources/faces/girls/Flavia_de_Oliveira.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Florence", "Faivre", "/resources/faces/girls/Florence_Faivre.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Gal", "Gadot", "/resources/faces/girls/Gal_Gadot.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Gemma", "Arterton", "/resources/faces/girls/Gemma_Arterton.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Genesis", "Rodriguez", "/resources/faces/girls/Genesis_Rodriguez.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Georgia", "King", "/resources/faces/girls/Georgia_King.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Gina", "Carano", "/resources/faces/girls/Gina_Carano.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Gisele", "Bundchen", "/resources/faces/girls/Gisele_Bundchen.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Gugu", "Mbatha-Raw", "/resources/faces/girls/Gugu_Mbatha-Raw.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Gwendoline", "Taylor", "/resources/faces/girls/Gwendoline_Taylor.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Gwyneth", "Paltrow", "/resources/faces/girls/Gwyneth_Paltrow.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Halle", "Berry", "/resources/faces/girls/Halle_Berry.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Hana", "Jirickova", "/resources/faces/girls/Hana_Jirickova.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Hana", "Soukupova", "/resources/faces/girls/Hana_Soukupova.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Hannah", "Marks", "/resources/faces/girls/Hannah_Marks.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Hayden", "Panettiere", "/resources/faces/girls/Hayden_Panettiere.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Heather", "Marks", "/resources/faces/girls/Heather_Marks.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Heather", "Morris", "/resources/faces/girls/Heather_Morris.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Heidi", "Klum", "/resources/faces/girls/Heidi_Klum.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Helena", "Christensen", "/resources/faces/girls/Helena_Christensen.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Hilary", "Rhoda", "/resources/faces/girls/Hilary_Rhoda.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Ingrid", "Graham", "/resources/faces/girls/Ingrid_Graham.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Isabel", "Lucas", "/resources/faces/girls/Isabel_Lucas.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Izabel", "Goulart", "/resources/faces/girls/Izabel_Goulart.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Jacqueline", "MacInnes Wood", "/resources/faces/girls/Jacqueline_MacInnes_Wood.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Jaime", "King", "/resources/faces/girls/Jaime_King.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Jaimie", "Alexander", "/resources/faces/girls/Jaimie_Alexander.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Jeisa", "Chiminazzo", "/resources/faces/girls/Jeisa_Chiminazzo.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Jenna", "Dewan-Tatum", "/resources/faces/girls/Jenna_Dewan-Tatum.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Jennifer", "Aniston", "/resources/faces/girls/Jennifer_Aniston.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Jennifer", "Connelly", "/resources/faces/girls/Jennifer_Connelly.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Jennifer", "Garner", "/resources/faces/girls/Jennifer_Garner.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Jennifer", "Kristin Cox", "/resources/faces/girls/Jennifer_Kristin_Cox.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Jennifer", "Lawrence", "/resources/faces/girls/Jennifer_Lawrence.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Jessica", "Alba", "/resources/faces/girls/Jessica_Alba.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Jessica", "Brown Findlay", "/resources/faces/girls/Jessica_Brown_Findlay.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Jessica", "Clark", "/resources/faces/girls/Jessica_Clark.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Jessica", "Lucas", "/resources/faces/girls/Jessica_Lucas.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Jessica", "Pare", "/resources/faces/girls/Jessica_Pare.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Jessica", "Parker Kennedy", "/resources/faces/girls/Jessica_Parker_Kennedy.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Jo", "Beth Locklear", "/resources/faces/girls/Jo_Beth_Locklear.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Jocelin", "Donahue", "/resources/faces/girls/Jocelin_Donahue.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Julia", "Benson", "/resources/faces/girls/Julia_Benson.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Julia", "Roberts", "/resources/faces/girls/Julia_Roberts.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Julia", "Stegner", "/resources/faces/girls/Julia_Stegner.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Julia", "Stiles", "/resources/faces/girls/Julia_Stiles.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Julia", "Voth", "/resources/faces/girls/Julia_Voth.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Julianne", "Moore", "/resources/faces/girls/Julianne_Moore.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Kalilah", "Harris", "/resources/faces/girls/Kalilah_Harris.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Karolina", "Kurkova", "/resources/faces/girls/Karolina_Kurkova.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Kat", "Dennings", "/resources/faces/girls/Kat_Dennings.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Kate", "Beckinsale", "/resources/faces/girls/Kate_Beckinsale.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Kate", "Hudson", "/resources/faces/girls/Kate_Hudson.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Kate", "Winslet", "/resources/faces/girls/Kate_Winslet.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Katherine", "Heigl", "/resources/faces/girls/Katherine_Heigl.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Katheryn", "Winnick", "/resources/faces/girls/Katheryn_Winnick.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Kathleen", "Robertson", "/resources/faces/girls/Kathleen_Robertson.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Katie", "Cassidy", "/resources/faces/girls/Katie_Cassidy.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Katie", "Powers", "/resources/faces/girls/Katie_Powers.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Katy", "Perry", "/resources/faces/girls/Katy_Perry.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Keira", "Knightley", "/resources/faces/girls/Keira_Knightley.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Keri", "Russell", "/resources/faces/girls/Keri_Russell.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Kerry", "Washington", "/resources/faces/girls/Kerry_Washington.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Kiele", "Sanchez", "/resources/faces/girls/Kiele_Sanchez.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Kirsten", "Dunst", "/resources/faces/girls/Kirsten_Dunst.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Kiva", "Dawson", "/resources/faces/girls/Kiva_Dawson.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Kristen", "Bell", "/resources/faces/girls/Kristen_Bell.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Kristen", "Stewart", "/resources/faces/girls/Kristen_Stewart.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Ksenia", "Solo", "/resources/faces/girls/Ksenia_Solo.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Laura", "Harring", "/resources/faces/girls/Laura_Harring.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Laura", "Mennell", "/resources/faces/girls/Laura_Mennell.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Laura", "Vandervoort", "/resources/faces/girls/Laura_Vandervoort.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Lauren", "Cohan", "/resources/faces/girls/Lauren_Cohan.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Lauren", "Jenkins", "/resources/faces/girls/Lauren_Jenkins.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Lauren", "Lee Smith", "/resources/faces/girls/Lauren_Lee_Smith.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Lauren", "Storm", "/resources/faces/girls/Lauren_Storm.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Laurence", "Leboeuf", "/resources/faces/girls/Laurence_Leboeuf.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Laurie", "Holden", "/resources/faces/girls/Laurie_Holden.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Lea", "Michele", "/resources/faces/girls/Lea_Michele.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Leda", "Lum", "/resources/faces/girls/Leda_Lum.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Leighton", "Meester", "/resources/faces/girls/Leighton_Meester.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Leila", "Lopes", "/resources/faces/girls/Leila_Lopes.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Lena", "Headey", "/resources/faces/girls/Lena_Headey.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Lesley-Ann", "Brandt", "/resources/faces/girls/Lesley-Ann_Brandt.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Lindsay", "Burdge", "/resources/faces/girls/Lindsay_Burdge.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Lisa", "Brenner", "/resources/faces/girls/Lisa_Brenner.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Lisa", "Chandler", "/resources/faces/girls/Lisa_Chandler.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Lisa", "Edelstein", "/resources/faces/girls/Lisa_Edelstein.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Lisamarie", "Costabile", "/resources/faces/girls/Lisamarie_Costabile.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Liv", "Tyler", "/resources/faces/girls/Liv_Tyler.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Liya", "Kebede", "/resources/faces/girls/Liya_Kebede.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Louise", "Monot", "/resources/faces/girls/Louise_Monot.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Lucy", "Hale", "/resources/faces/girls/Lucy_Hale.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Lymari", "Nadal", "/resources/faces/girls/Lymari_Nadal.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Maggie", "Grace", "/resources/faces/girls/Maggie_Grace.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Maggie", "Gyllenhaal", "/resources/faces/girls/Maggie_Gyllenhaal.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Malaya", "Rivera Drew", "/resources/faces/girls/Malaya_Rivera_Drew.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Margo", "Harshman", "/resources/faces/girls/Margo_Harshman.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Margot", "Robbie", "/resources/faces/girls/Margot_Robbie.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Maria", "Grazia Cucinotta", "/resources/faces/girls/Maria_Grazia_Cucinotta.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Marion", "Cotillard", "/resources/faces/girls/Marion_Cotillard.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Marnette", "Patterson", "/resources/faces/girls/Marnette_Patterson.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Mary", "Elizabeth Winstead", "/resources/faces/girls/Mary_Elizabeth_Winstead.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Megan", "Fox", "/resources/faces/girls/Megan_Fox.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("", "Melanie-Minichino", "/resources/faces/girls/Melanie-Minichino.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Melissa", "Joan Hart", "/resources/faces/girls/Melissa_Joan_Hart.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Mia", "Sara", "/resources/faces/girls/Mia_Sara.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Michaela", "McManus", "/resources/faces/girls/Michaela_McManus.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Michelle", "Borth", "/resources/faces/girls/Michelle_Borth.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Mila", "Kunis", "/resources/faces/girls/Mila_Kunis.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Miranda", "Kerr", "/resources/faces/girls/Miranda_Kerr.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Mischa", "Barton", "/resources/faces/girls/Mischa_Barton.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Missy", "Peregrym", "/resources/faces/girls/Missy_Peregrym.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Monica", "Bellucci", "/resources/faces/girls/Monica_Bellucci.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Montserrat", "Oliver", "/resources/faces/girls/Montserrat_Oliver.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Morena", "Baccarin", "/resources/faces/girls/Morena_Baccarin.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Najwa", "Nimri", "/resources/faces/girls/Najwa_Nimri.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Nash", "Carter", "/resources/faces/girls/Nash_Carter.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Natalia", "Tena", "/resources/faces/girls/Natalia_Tena.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Natalie", "Martinez", "/resources/faces/girls/Natalie_Martinez.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Natalie", "Portman", "/resources/faces/girls/Natalie_Portman.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Natasha", "Henstridge", "/resources/faces/girls/Natasha_Henstridge.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Nazneen", "Contractor", "/resources/faces/girls/Nazneen_Contractor.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Nicole", "de Boer", "/resources/faces/girls/Nicole_de_Boer.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Nicole", "Kidman", "/resources/faces/girls/Nicole_Kidman.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Nihan", "Gur", "/resources/faces/girls/Nihan_Gur.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Nikki", "Reed", "/resources/faces/girls/Nikki_Reed.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Nikki", "Wallin", "/resources/faces/girls/Nikki_Wallin.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Nina", "Dobrev", "/resources/faces/girls/Nina_Dobrev.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Odette", "Annable", "/resources/faces/girls/Odette_Annable.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Olga", "Kurylenko", "/resources/faces/girls/Olga_Kurylenko.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Olivia", "Thirlby", "/resources/faces/girls/Olivia_Thirlby.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Olivia", "Wilde", "/resources/faces/girls/Olivia_Wilde.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Paris", "Hilton", "/resources/faces/girls/Paris_Hilton.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Paz", "Vega", "/resources/faces/girls/Paz_Vega.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Penelope", "Cruz", "/resources/faces/girls/Penelope_Cruz.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Phoebe", "Tonkin", "/resources/faces/girls/Phoebe_Tonkin.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Piper", "Perabo", "/resources/faces/girls/Piper_Perabo.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Poppy", "Corby-Tuech", "/resources/faces/girls/Poppy_Corby-Tuech.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Rachel", "Bilson", "/resources/faces/girls/Rachel_Bilson.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Rachel", "Hurd-Wood", "/resources/faces/girls/Rachel_Hurd-Wood.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Rachel", "McAdams", "/resources/faces/girls/Rachel_McAdams.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Rachel", "Roberts", "/resources/faces/girls/Rachel_Roberts.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Rachelle", "Lefevre", "/resources/faces/girls/Rachelle_Lefevre.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Raquel", "Alessi", "/resources/faces/girls/Raquel_Alessi.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Rebecca", "Hall", "/resources/faces/girls/Rebecca_Hall.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Rebecca", "Mader", "/resources/faces/girls/Rebecca_Mader.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Rebecca", "Romijn", "/resources/faces/girls/Rebecca_Romijn.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Reem", "Kadem", "/resources/faces/girls/Reem_Kadem.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Rene", "Russo", "/resources/faces/girls/Rene_Russo.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Reynah", "Oppal", "/resources/faces/girls/Reynah_Oppal.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Rhiana", "Griffith", "/resources/faces/girls/Rhiana_Griffith.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Rooney", "Mara", "/resources/faces/girls/Rooney_Mara.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Rosario", "Dawson", "/resources/faces/girls/Rosario_Dawson.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Rose", "Leslie", "/resources/faces/girls/Rose_Leslie.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Rose", "McGowan", "/resources/faces/girls/Rose_McGowan.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Roselyn", "Sanchez", "/resources/faces/girls/Roselyn_Sanchez.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Rosie", "Huntington-Whiteley", "/resources/faces/girls/Rosie_Huntington-Whiteley.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Roxane", "Mesquida", "/resources/faces/girls/Roxane_Mesquida.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Salma", "Hayek", "/resources/faces/girls/Salma_Hayek.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Sandy", "Colton", "/resources/faces/girls/Sandy_Colton.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Sara", "Canning", "/resources/faces/girls/Sara_Canning.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Sarah", "Wayne Callies", "/resources/faces/girls/Sarah_Wayne_Callies.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Sarah-Jeanne", "Labrosse", "/resources/faces/girls/Sarah-Jeanne_Labrosse.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Sasha", "Barrese", "/resources/faces/girls/Sasha_Barrese.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Scarlett", "Johansson", "/resources/faces/girls/Scarlett_Johansson.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Selita", "Ebanks", "/resources/faces/girls/Selita_Ebanks.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Serinda", "Swan", "/resources/faces/girls/Serinda_Swan.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("", "Shakira", "/resources/faces/girls/Shakira.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Shay", "Mitchell", "/resources/faces/girls/Shay_Mitchell.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Sofia", "Vergara", "/resources/faces/girls/Sofia_Vergara.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Sonia", "Vera", "/resources/faces/girls/Sonia_Vera.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Sophie", "Turner", "/resources/faces/girls/Sophie_Turner.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Stana", "Katic", "/resources/faces/girls/Stana_Katic.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Taylor", "Swift", "/resources/faces/girls/Taylor_Swift.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Teresa", "Palmer", "/resources/faces/girls/Teresa_Palmer.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Thandie", "Newton", "/resources/faces/girls/Thandie_Newton.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Tika", "Sumpter", "/resources/faces/girls/Tika_Sumpter.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Traci", "Dinwiddie", "/resources/faces/girls/Traci_Dinwiddie.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Tracy", "Spiridakos", "/resources/faces/girls/Tracy_Spiridakos.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Tricia", "Helfer", "/resources/faces/girls/Tricia_Helfer.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Tuppence", "Middleton", "/resources/faces/girls/Tuppence_Middleton.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Uma", "Thurman", "/resources/faces/girls/Uma_Thurman.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Valerie", "Azlynn", "/resources/faces/girls/Valerie_Azlynn.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Vanessa", "Lengies", "/resources/faces/girls/Vanessa_Lengies.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Victoria", "Gracie", "/resources/faces/girls/Victoria_Gracie.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Violante", "Placido", "/resources/faces/girls/Violante_Placido.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Virginia", "Bowers", "/resources/faces/girls/Virginia_Bowers.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Willa", "Holland", "/resources/faces/girls/Willa_Holland.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Winona", "Ryder", "/resources/faces/girls/Winona_Ryder.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Yanelba", "Ferreira", "/resources/faces/girls/Yanelba_Ferreira.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Yasmin", "Le Bon", "/resources/faces/girls/Yasmin_Le_Bon.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Yunjin", "Kim", "/resources/faces/girls/Yunjin_Kim.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Zana", "Salobir", "/resources/faces/girls/Zana_Salobir.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Zoe", "Saldana", "/resources/faces/girls/Zoe_Saldana.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Zoie", "Palmer", "/resources/faces/girls/Zoie_Palmer.jpg");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Zooey", "Deschanel", "/resources/faces/girls/Zooey_Deschanel.jpg");
		girlsFaceMap.put(face.getId(), face);

		//boys
		face = new Face("Aaron", "Eckhart", "/resources/faces/boys/Aaron_Eckhart.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Aaron", "Schwartz", "/resources/faces/boys/Aaron_Schwartz.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Adam", "Sandler", "/resources/faces/boys/Adam_Sandler.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Adrien", "Brody", "/resources/faces/boys/Adrien_Brody.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Al", "Pacino", "/resources/faces/boys/Al_Pacino.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Alan", "Rickman", "/resources/faces/boys/Alan_Rickman.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Alec", "Baldwin", "/resources/faces/boys/Alec_Baldwin.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Alex", "Pettyfer", "/resources/faces/boys/Alex_Pettyfer.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Andrew", "Divoff", "/resources/faces/boys/Andrew_Divoff.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Andrew", "Garfield", "/resources/faces/boys/Andrew_Garfield.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Andrew", "Lincoln", "/resources/faces/boys/Andrew_Lincoln.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Anthony", "Hopkins", "/resources/faces/boys/Anthony_Hopkins.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Anthony", "Mackie", "/resources/faces/boys/Anthony_Mackie.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Anton", "Yelchin", "/resources/faces/boys/Anton_Yelchin.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Antonio", "Banderas", "/resources/faces/boys/Antonio_Banderas.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Arnold", "Schwarzenegger", "/resources/faces/boys/Arnold_Schwarzenegger.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Ben", "Affleck", "/resources/faces/boys/Ben_Affleck.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Ben", "Foster", "/resources/faces/boys/Ben_Foster.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Ben", "Kingsley", "/resources/faces/boys/Ben_Kingsley.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Ben", "Stiller", "/resources/faces/boys/Ben_Stiller.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Benedict", "Cumberbatch", "/resources/faces/boys/Benedict_Cumberbatch.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Bill", "Murray", "/resources/faces/boys/Bill_Murray.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Brad", "Pitt", "/resources/faces/boys/Brad_Pitt.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Bradley", "Cooper", "/resources/faces/boys/Bradley_Cooper.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Brendan", "Gleeson", "/resources/faces/boys/Brendan_Gleeson.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Brett", "Cullen", "/resources/faces/boys/Brett_Cullen.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Brian", "Tee", "/resources/faces/boys/Brian_Tee.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Bruce", "Davison", "/resources/faces/boys/Bruce_Davison.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Bruce", "Willis", "/resources/faces/boys/Bruce_Willis.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Cam", "Gigandet", "/resources/faces/boys/Cam_Gigandet.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Casey", "Affleck", "/resources/faces/boys/Casey_Affleck.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Chace", "Crawford", "/resources/faces/boys/Chace_Crawford.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Channing", "Tatum", "/resources/faces/boys/Channing_Tatum.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Charlie", "Sheen", "/resources/faces/boys/Charlie_Sheen.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Chris", "Cooper", "/resources/faces/boys/Chris_Cooper.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Chris", "Evans", "/resources/faces/boys/Chris_Evans.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Chris", "Hemsworth", "/resources/faces/boys/Chris_Hemsworth.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Chris", "Lowell", "/resources/faces/boys/Chris_Lowell.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Chris", "ODonnell", "/resources/faces/boys/Chris_ODonnell.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Chris", "Penn", "/resources/faces/boys/Chris_Penn.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Chris", "Pine", "/resources/faces/boys/Chris_Pine.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Christian", "Bale", "/resources/faces/boys/Christian_Bale.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Christoph", "Waltz", "/resources/faces/boys/Christoph_Waltz.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Christopher", "Lambert", "/resources/faces/boys/Christopher_Lambert.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Christopher", "Lee", "/resources/faces/boys/Christopher_Lee.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Christopher", "Walken", "/resources/faces/boys/Christopher_Walken.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Cillian", "Murphy", "/resources/faces/boys/Cillian_Murphy.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Clint", "Eastwood", "/resources/faces/boys/Clint_Eastwood.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Clive", "Owen", "/resources/faces/boys/Clive_Owen.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Colin", "Farrell", "/resources/faces/boys/Colin_Farrell.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Colin", "Firth", "/resources/faces/boys/Colin_Firth.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Colm", "Feore", "/resources/faces/boys/Colm_Feore.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Colton", "Haynes", "/resources/faces/boys/Colton_Haynes.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Dan", "Aykroyd", "/resources/faces/boys/Dan_Aykroyd.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Dane", "Cook", "/resources/faces/boys/Dane_Cook.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Daniel", "Craig", "/resources/faces/boys/Daniel_Craig.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Daniel", "Dae Kim", "/resources/faces/boys/Daniel_Dae_Kim.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Daniel", "Day-Lewis", "/resources/faces/boys/Daniel_Day-Lewis.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Daniel", "Radcliffe", "/resources/faces/boys/Daniel_Radcliffe.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Danny", "DeVito", "/resources/faces/boys/Danny_DeVito.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Danny", "Huston", "/resources/faces/boys/Danny_Huston.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("David", "Oakes", "/resources/faces/boys/David_Oakes.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("David", "Wenham", "/resources/faces/boys/David_Wenham.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Dennis", "Quaid", "/resources/faces/boys/Dennis_Quaid.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Denzel", "Washington", "/resources/faces/boys/Denzel_Washington.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Dominic", "Cooper", "/resources/faces/boys/Dominic_Cooper.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Dominic", "Monaghan", "/resources/faces/boys/Dominic_Monaghan.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Dominic", "Rains", "/resources/faces/boys/Dominic_Rains.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Don", "Cheadle", "/resources/faces/boys/Don_Cheadle.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Donald", "Sutherland", "/resources/faces/boys/Donald_Sutherland.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Dustin", "Hoffman", "/resources/faces/boys/Dustin_Hoffman.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Dustin", "Milligan", "/resources/faces/boys/Dustin_Milligan.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Dylan", "Walsh", "/resources/faces/boys/Dylan_Walsh.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Ed", "Harris", "/resources/faces/boys/Ed_Harris.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Ed", "Westwick", "/resources/faces/boys/Ed_Westwick.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Eddie", "Murphy", "/resources/faces/boys/Eddie_Murphy.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Edi", "Gathegi", "/resources/faces/boys/Edi_Gathegi.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Edward", "Norton", "/resources/faces/boys/Edward_Norton.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Elijah", "Wood", "/resources/faces/boys/Elijah_Wood.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("", "Eminem", "/resources/faces/boys/Eminem.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Eric", "Bana", "/resources/faces/boys/Eric_Bana.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Ethan", "Hawke", "/resources/faces/boys/Ethan_Hawke.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Eugene", "Byrd", "/resources/faces/boys/Eugene_Byrd.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Ewan", "McGregor", "/resources/faces/boys/Ewan_McGregor.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Faran", "Tahir", "/resources/faces/boys/Faran_Tahir.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Forest", "Whitaker", "/resources/faces/boys/Forest_Whitaker.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Frank", "Grillo", "/resources/faces/boys/Frank_Grillo.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Garrett", "Hedlund", "/resources/faces/boys/Garrett_Hedlund.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Gary", "Oldman", "/resources/faces/boys/Gary_Oldman.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("George", "Clooney", "/resources/faces/boys/George_Clooney.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Gerard", "Butler", "/resources/faces/boys/Gerard_Butler.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Giovanni", "Ribisi", "/resources/faces/boys/Giovanni_Ribisi.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Greg", "Kinnear", "/resources/faces/boys/Greg_Kinnear.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Guy", "Pearce", "/resources/faces/boys/Guy_Pearce.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Harrison", "Ford", "/resources/faces/boys/Harrison_Ford.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Harvey", "Keitel", "/resources/faces/boys/Harvey_Keitel.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Henry", "Cavill", "/resources/faces/boys/Henry_Cavill.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Henry", "Ian Cusick", "/resources/faces/boys/Henry_Ian_Cusick.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Hugh", "Dancy", "/resources/faces/boys/Hugh_Dancy.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Hugh", "Jackman", "/resources/faces/boys/Hugh_Jackman.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Hugh", "Laurie", "/resources/faces/boys/Hugh_Laurie.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Ian", "Holm", "/resources/faces/boys/Ian_Holm.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Ian", "Somerhalder", "/resources/faces/boys/Ian_Somerhalder.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Idris", "Elba", "/resources/faces/boys/Idris_Elba.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Isaac", "Hempstead Wright", "/resources/faces/boys/Isaac_Hempstead_Wright.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jack", "Black", "/resources/faces/boys/Jack_Black.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jack", "Gleeson", "/resources/faces/boys/Jack_Gleeson.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jack", "Nicholson", "/resources/faces/boys/Jack_Nicholson.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jackie", "Chan", "/resources/faces/boys/Jackie_Chan.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("James", "Cromwell", "/resources/faces/boys/James_Cromwell.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("James", "Franco", "/resources/faces/boys/James_Franco.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("James", "McAvoy", "/resources/faces/boys/James_McAvoy.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("James", "Phelps", "/resources/faces/boys/James_Phelps.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jamie", "Dornan", "/resources/faces/boys/Jamie_Dornan.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jamie", "Foxx", "/resources/faces/boys/Jamie_Foxx.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jared", "Leto", "/resources/faces/boys/Jared_Leto.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jason", "Flemyng", "/resources/faces/boys/Jason_Flemyng.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jason", "Isaacs", "/resources/faces/boys/Jason_Isaacs.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jason", "Segel", "/resources/faces/boys/Jason_Segel.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jason", "Statham", "/resources/faces/boys/Jason_Statham.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jean", "Reno", "/resources/faces/boys/Jean_Reno.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jeff", "Bridges", "/resources/faces/boys/Jeff_Bridges.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jeff", "Fahey", "/resources/faces/boys/Jeff_Fahey.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jeffrey", "Dean Morgan", "/resources/faces/boys/Jeffrey_Dean_Morgan.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jensen", "Ackles", "/resources/faces/boys/Jensen_Ackles.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jeremy", "Irons", "/resources/faces/boys/Jeremy_Irons.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jeremy", "Renner", "/resources/faces/boys/Jeremy_Renner.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jesse", "Eisenberg", "/resources/faces/boys/Jesse_Eisenberg.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jesse", "Spencer", "/resources/faces/boys/Jesse_Spencer.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jet", "Li", "/resources/faces/boys/Jet_Li.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jim", "Carrey", "/resources/faces/boys/Jim_Carrey.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jim", "Caviezel", "/resources/faces/boys/Jim_Caviezel.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("JJ", "Feild", "/resources/faces/boys/JJ_Feild.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("JK", "Simmons", "/resources/faces/boys/JK_Simmons.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Joaquin", "Phoenix", "/resources/faces/boys/Joaquin_Phoenix.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Joe", "Manganiello", "/resources/faces/boys/Joe_Manganiello.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("John", "Carroll Lynch", "/resources/faces/boys/John_Carroll_Lynch.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("John", "Cusack", "/resources/faces/boys/John_Cusack.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("John", "Malkovich", "/resources/faces/boys/John_Malkovich.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("John", "Travolta", "/resources/faces/boys/John_Travolta.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Johnny", "Depp", "/resources/faces/boys/Johnny_Depp.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Johnny", "Whitworth", "/resources/faces/boys/Johnny_Whitworth.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jon", "Favreau", "/resources/faces/boys/Jon_Favreau.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jon", "Voight", "/resources/faces/boys/Jon_Voight.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jonah", "Hill", "/resources/faces/boys/Jonah_Hill.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jorge", "Garcia", "/resources/faces/boys/Jorge_Garcia.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Joseph", "Gordon-Levitt", "/resources/faces/boys/Joseph_Gordon-Levitt.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Josh", "Brolin", "/resources/faces/boys/Josh_Brolin.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Josh", "Dallas", "/resources/faces/boys/Josh_Dallas.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Josh", "Duhamel", "/resources/faces/boys/Josh_Duhamel.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Josh", "Hartnett", "/resources/faces/boys/Josh_Hartnett.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Josh", "Henderson", "/resources/faces/boys/Josh_Henderson.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Josh", "Holloway", "/resources/faces/boys/Josh_Holloway.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Josh", "Lucas", "/resources/faces/boys/Josh_Lucas.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jude", "Law", "/resources/faces/boys/Jude_Law.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Julian", "McMahon", "/resources/faces/boys/Julian_McMahon.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Justin", "Long", "/resources/faces/boys/Justin_Long.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Justin", "Timberlake", "/resources/faces/boys/Justin_Timberlake.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Karl", "Urban", "/resources/faces/boys/Karl_Urban.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Keanu", "Reeves", "/resources/faces/boys/Keanu_Reeves.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Kellan", "Lutz", "/resources/faces/boys/Kellan_Lutz.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Ken", "Leung", "/resources/faces/boys/Ken_Leung.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Ken", "Watanabe", "/resources/faces/boys/Ken_Watanabe.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Kett", "Turton", "/resources/faces/boys/Kett_Turton.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Kevin", "Bacon", "/resources/faces/boys/Kevin_Bacon.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Kevin", "Costner", "/resources/faces/boys/Kevin_Costner.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Kevin", "Durand", "/resources/faces/boys/Kevin_Durand.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Kevin", "Spacey", "/resources/faces/boys/Kevin_Spacey.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Kevin", "Zegers", "/resources/faces/boys/Kevin_Zegers.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Kiefer", "Sutherland", "/resources/faces/boys/Kiefer_Sutherland.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Kit", "Harington", "/resources/faces/boys/Kit_Harington.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Kris", "Kristofferson", "/resources/faces/boys/Kris_Kristofferson.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Kristian", "Nairn", "/resources/faces/boys/Kristian_Nairn.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Kurt", "Russell", "/resources/faces/boys/Kurt_Russell.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Kyle", "Gallner", "/resources/faces/boys/Kyle_Gallner.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Laurence", "Fishburne", "/resources/faces/boys/Laurence_Fishburne.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Leonardo", "DiCaprio", "/resources/faces/boys/Leonardo_DiCaprio.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Liam", "Cunningham", "/resources/faces/boys/Liam_Cunningham.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Liam", "Hemsworth", "/resources/faces/boys/Liam_Hemsworth.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Liam", "Neeson", "/resources/faces/boys/Liam_Neeson.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Linus", "Roache", "/resources/faces/boys/Linus_Roache.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Logan", "Marshall-Green", "/resources/faces/boys/Logan_Marshall-Green.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Lucas", "Till", "/resources/faces/boys/Lucas_Till.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Luke", "Wilson", "/resources/faces/boys/Luke_Wilson.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Macaulay", "Culkin", "/resources/faces/boys/Macaulay_Culkin.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Mads", "Mikkelsen", "/resources/faces/boys/Mads_Mikkelsen.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Mark", "Gantt", "/resources/faces/boys/Mark_Gantt.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Mark", "Ruffalo", "/resources/faces/boys/Mark_Ruffalo.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Mark", "Wahlberg", "/resources/faces/boys/Mark_Wahlberg.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Martin", "Lawrence", "/resources/faces/boys/Martin_Lawrence.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Martin", "Sheen", "/resources/faces/boys/Martin_Sheen.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Matt", "Bomer", "/resources/faces/boys/Matt_Bomer.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Matt", "Czuchry", "/resources/faces/boys/Matt_Czuchry.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Matt", "Damon", "/resources/faces/boys/Matt_Damon.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Matt", "Lanter", "/resources/faces/boys/Matt_Lanter.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Matthew", "Fox", "/resources/faces/boys/Matthew_Fox.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Matthew", "McConaughey", "/resources/faces/boys/Matthew_McConaughey.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Matthew", "Perry", "/resources/faces/boys/Matthew_Perry.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Max", "Irons", "/resources/faces/boys/Max_Irons.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Max", "Thieriot", "/resources/faces/boys/Max_Thieriot.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Max", "von Sydow", "/resources/faces/boys/Max_von_Sydow.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Mel", "Gibson", "/resources/faces/boys/Mel_Gibson.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Michael", "C Hall", "/resources/faces/boys/Michael_C_Hall.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Michael", "Caine", "/resources/faces/boys/Michael_Caine.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Michael", "Douglas", "/resources/faces/boys/Michael_Douglas.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Michael", "Emerson", "/resources/faces/boys/Michael_Emerson.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Michael", "Fassbender", "/resources/faces/boys/Michael_Fassbender.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Michael", "Madsen", "/resources/faces/boys/Michael_Madsen.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Michael", "Pitt", "/resources/faces/boys/Michael_Pitt.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Michael", "Sheen", "/resources/faces/boys/Michael_Sheen.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Mickey", "Rourke", "/resources/faces/boys/Mickey_Rourke.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Milo", "Ventimiglia", "/resources/faces/boys/Milo_Ventimiglia.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Morgan", "Freeman", "/resources/faces/boys/Morgan_Freeman.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Nathan", "Fillion", "/resources/faces/boys/Nathan_Fillion.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Naveen", "Andrews", "/resources/faces/boys/Naveen_Andrews.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Neal", "McDonough", "/resources/faces/boys/Neal_McDonough.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Neil", "Patrick Harris", "/resources/faces/boys/Neil_Patrick_Harris.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Niall", "Matter", "/resources/faces/boys/Niall_Matter.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Nicholas", "Hoult", "/resources/faces/boys/Nicholas_Hoult.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Nicolas", "Cage", "/resources/faces/boys/Nicolas_Cage.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Nikolaj", "Coster Waldu", "/resources/faces/boys/Nikolaj_Coster_Waldu.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Oliver", "Phelps", "/resources/faces/boys/Oliver_Phelps.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Orlando", "Bloom", "/resources/faces/boys/Orlando_Bloom.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Owen", "Wilson", "/resources/faces/boys/Owen_Wilson.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Patrick", "Stewart", "/resources/faces/boys/Patrick_Stewart.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Patrick", "Wilson", "/resources/faces/boys/Patrick_Wilson.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Paul", "Bettany", "/resources/faces/boys/Paul_Bettany.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Paul", "Dano", "/resources/faces/boys/Paul_Dano.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Paul", "Giamatti", "/resources/faces/boys/Paul_Giamatti.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Paul", "Rudd", "/resources/faces/boys/Paul_Rudd.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Paul", "Walker", "/resources/faces/boys/Paul_Walker.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Penn", "Badgley", "/resources/faces/boys/Penn_Badgley.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Peter", "Dinklage", "/resources/faces/boys/Peter_Dinklage.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Peter", "Facinelli", "/resources/faces/boys/Peter_Facinelli.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Pierce", "Brosnan", "/resources/faces/boys/Pierce_Brosnan.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Quentin", "Tarantino", "/resources/faces/boys/Quentin_Tarantino.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Ralph", "Fiennes", "/resources/faces/boys/Ralph_Fiennes.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Ray", "Park", "/resources/faces/boys/Ray_Park.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Richard", "Gere", "/resources/faces/boys/Richard_Gere.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Rob", "Lowe", "/resources/faces/boys/Rob_Lowe.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Robert", "De Niro", "/resources/faces/boys/Robert_De_Niro.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Robert", "Downey Jr", "/resources/faces/boys/Robert_Downey_Jr.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Robert", "Duvall", "/resources/faces/boys/Robert_Duvall.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Robert", "Knepper", "/resources/faces/boys/Robert_Knepper.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Robert", "Pattinson", "/resources/faces/boys/Robert_Pattinson.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Robert", "Sean Leonard", "/resources/faces/boys/Robert_Sean_Leonard.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Robin", "Williams", "/resources/faces/boys/Robin_Williams.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Rupert", "Grint", "/resources/faces/boys/Rupert_Grint.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Russell", "Crowe", "/resources/faces/boys/Russell_Crowe.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Ryan", "Gosling", "/resources/faces/boys/Ryan_Gosling.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Ryan", "Reynolds", "/resources/faces/boys/Ryan_Reynolds.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Sam", "Rockwell", "/resources/faces/boys/Sam_Rockwell.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Samuel", "L Jackson", "/resources/faces/boys/Samuel_L_Jackson.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Scott", "Caan", "/resources/faces/boys/Scott_Caan.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Scott", "Speedman", "/resources/faces/boys/Scott_Speedman.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Sean", "Bean", "/resources/faces/boys/Sean_Bean.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Sean", "Connery", "/resources/faces/boys/Sean_Connery.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Sean", "Penn", "/resources/faces/boys/Sean_Penn.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Seth", "Rogen", "/resources/faces/boys/Seth_Rogen.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Shawn", "Ashmore", "/resources/faces/boys/Shawn_Ashmore.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Shia", "LaBeouf", "/resources/faces/boys/Shia_LaBeouf.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Simon", "Baker", "/resources/faces/boys/Simon_Baker.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Simon", "Pegg", "/resources/faces/boys/Simon_Pegg.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Stanley", "Tucci", "/resources/faces/boys/Stanley_Tucci.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Stephen", "Dorff", "/resources/faces/boys/Stephen_Dorff.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Steve", "Buscemi", "/resources/faces/boys/Steve_Buscemi.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Steve", "Carell", "/resources/faces/boys/Steve_Carell.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Steve", "Martin", "/resources/faces/boys/Steve_Martin.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Sylvester", "Stallone", "/resources/faces/boys/Sylvester_Stallone.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Tadanobu", "Asano", "/resources/faces/boys/Tadanobu_Asano.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Taylor", "Lautner", "/resources/faces/boys/Taylor_Lautner.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Terence", "Stamp", "/resources/faces/boys/Terence_Stamp.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Terrence", "Howard", "/resources/faces/boys/Terrence_Howard.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Terry", "OQuinn", "/resources/faces/boys/Terry_OQuinn.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Thomas", "Jane", "/resources/faces/boys/Thomas_Jane.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Tim", "Roth", "/resources/faces/boys/Tim_Roth.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Tobey", "Maguire", "/resources/faces/boys/Tobey_Maguire.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Tom", "Cruise", "/resources/faces/boys/Tom_Cruise.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Tom", "Felton", "/resources/faces/boys/Tom_Felton.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Tom", "Hanks", "/resources/faces/boys/Tom_Hanks.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Tom", "Hardy", "/resources/faces/boys/Tom_Hardy.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Tom", "Hiddleston", "/resources/faces/boys/Tom_Hiddleston.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Tom", "Welling", "/resources/faces/boys/Tom_Welling.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Tom", "Wlaschiha", "/resources/faces/boys/Tom_Wlaschiha.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Tommy", "Lee Jones", "/resources/faces/boys/Tommy_Lee_Jones.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Topher", "Grace", "/resources/faces/boys/Topher_Grace.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Tyler", "Mane", "/resources/faces/boys/Tyler_Mane.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Viggo", "Mortensen", "/resources/faces/boys/Viggo_Mortensen.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Vin", "Diesel", "/resources/faces/boys/Vin_Diesel.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Vincent", "Cassel", "/resources/faces/boys/Vincent_Cassel.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Vincent", "Regan", "/resources/faces/boys/Vincent_Regan.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Vinnie", "Jones", "/resources/faces/boys/Vinnie_Jones.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Wentworth", "Miller", "/resources/faces/boys/Wentworth_Miller.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Wes", "Bentley", "/resources/faces/boys/Wes_Bentley.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Wesley", "Snipes", "/resources/faces/boys/Wesley_Snipes.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Will", "Ferrell", "/resources/faces/boys/Will_Ferrell.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Will", "Patton", "/resources/faces/boys/Will_Patton.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Will", "Smith", "/resources/faces/boys/Will_Smith.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Will", "Yun Lee", "/resources/faces/boys/Will_Yun_Lee.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Willem", "Dafoe", "/resources/faces/boys/Willem_Dafoe.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("William", "Fichtner", "/resources/faces/boys/William_Fichtner.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("William", "Forsythe", "/resources/faces/boys/William_Forsythe.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("William", "Hurt", "/resources/faces/boys/William_Hurt.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("William", "Sadler", "/resources/faces/boys/William_Sadler.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Woody", "Allen", "/resources/faces/boys/Woody_Allen.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Woody", "Harrelson", "/resources/faces/boys/Woody_Harrelson.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Xavier", "Samuel", "/resources/faces/boys/Xavier_Samuel.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Yul", "Vazquez", "/resources/faces/boys/Yul_Vazquez.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Zac", "Efron", "/resources/faces/boys/Zac_Efron.jpg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Zachary", "Quinto", "/resources/faces/boys/Zachary_Quinto.jpg");
		boysFaceMap.put(face.getId(), face);

		girlsFaceIdArray = new long[girlsFaceMap.size()];
		int girlsCount = girlsFaceIdArray.length;
		for (int i = 0; i < girlsCount; ++i) {
			girlsFaceIdArray[i] = i + 1;
		}

		boysFaceIdArray = new long[boysFaceMap.size()];
		int boysCount = boysFaceIdArray.length;
		for (int i = 0; i < boysCount; ++i) {
			boysFaceIdArray[i] = i + 1 + girlsCount;
		}
	}
}

class LruCache<A, B> extends LinkedHashMap<A, B> implements Serializable {
	private final int maxEntries;

	public LruCache(final int maxEntries) {
		super(maxEntries + 1, 1.0f, true);
		this.maxEntries = maxEntries;
	}

	/**
	 * Returns <tt>true</tt> if this <code>LruCache</code> has more entries than the maximum specified when it was
	 * created.
	 *
	 * <p>
	 * This method <em>does not</em> modify the underlying <code>Map</code>; it relies on the implementation of
	 * <code>LinkedHashMap</code> to do that, but that behavior is documented in the JavaDoc for
	 * <code>LinkedHashMap</code>.
	 * </p>
	 *
	 * @param eldest
	 *            the <code>Entry</code> in question; this implementation doesn't care what it is, since the
	 *            implementation is only dependent on the size of the cache
	 * @return <tt>true</tt> if the oldest
	 * @see java.util.LinkedHashMap#removeEldestEntry(Map.Entry)
	 */
	@Override
	protected boolean removeEldestEntry(final Map.Entry<A, B> eldest) {
		return super.size() > maxEntries;
	}
}
